const config = {
   ASPECT_RATIO: 16 / 9,
   HORIZONTAL_MOVEMENT_SPEED_MODIFIER: 0.07,
   GRAVITY_MODIFIER: 0.018,
   PARTICLE_GRAVITY_MODIFIER: 0.2,
   JUMP_VELOCITY_MODIFIER: 0.3,
   JUMP_SPIN_VELOCITY: 15,
   BLOCK_DISTANCE_FROM_LEFT_BORDER: 2,
   GLOBAL_GAME_SPEED_MULTIPLIER: 1.1, // AFFECTS GRAVITY, JUMP, HORIZONTAL MOVEMENT SPEED

   PLATFORM_JUMP_MULTIPLIER: 1.5
}

export default config