const config = {
   ASPECT_RATIO: 16 / 9,
   HORIZONTAL_MOVEMENT_SPEED_MODIFIER: 6,
   GRAVITY_MODIFIER: 1.5,
   PARTICLE_GRAVITY_MODIFIER: 0.2,
   JUMP_VELOCITY_MODIFIER: 0.3,
   JUMP_SPIN_VELOCITY: 10,
   BLOCK_DISTANCE_FROM_LEFT_BORDER: 8,
   GLOBAL_GAME_SPEED_MULTIPLIER: 1.1, // AFFECTS GRAVITY, JUMP, HORIZONTAL MOVEMENT SPEED

   PLAYER_JUMP_ROTATION: 180,
   PLAYER_SLIDEOFF_ROTATION: 90,
   PLAYER_PLATFORM_JUMP_ROTATION: 360,

   PLATFORM_JUMP_MULTIPLIER: 1.5,

   TEXT_SIZE_MODIFIER: 0.03,
}

export default config