const config = {
   ASPECT_RATIO: 16 / 9,
   HORIZONTAL_MOVEMENT_SPEED_MODIFIER: 0.09,
   GRAVITY_MODIFIER: 0.022,
   PARTICLE_GRAVITY_MODIFIER: 0.2,
   JUMP_VELOCITY_MODIFIER: 0.3,
   JUMP_SPIN_VELOCITY: 10,
   BLOCK_DISTANCE_FROM_LEFT_BORDER: 2,
   GLOBAL_GAME_SPEED_MULTIPLIER: 1.1, // AFFECTS GRAVITY, JUMP, HORIZONTAL MOVEMENT SPEED

   PLAYER_JUMP_ROTATION: 180,
   PLAYER_SLIDEOFF_ROTATION: 90,
   PLAYER_PLATFORM_JUMP_ROTATION: 360,

   PLATFORM_JUMP_MULTIPLIER: 1.5
}

export default config